name: Save PR Payload
on: ['issue_comment']

jobs:
  test:
    name: see-output
    runs-on: ubuntu-latest

    steps:
    - name: Write payload
      run: cat $GITHUB_EVENT_PATH > payload.json
    - name: Upload payload
      uses: actions/upload-artifact@v1
      with:
        name: payload
        path: payload.json
          
    - name: echo stuff
      run: |
        PR_NUMBER=$(jq -r ".issue.number" "$GITHUB_EVENT_PATH")
        echo "$PR_NUMBER"
