name: Tests
on: [push]

jobs:
  test-static-payload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: ./
        env:
          INPUT_TEST_EVENT_PATH: mock_data/payload.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TRIGGER_PHRASE: "/start-test-run"
          INPUT_PR_ACKNOWLEDGEMENT_LABEL: "test-label"
          DEBUG: true